MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class CreateModel : PageModel
    {
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
        }

        public RedirectToPageResult OnPost(ArticleCategoryCreate model)
        {
            _articleCategoryApplication.Create(model);
          return RedirectToPage("./List");
            
        }
    }
}

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public ArticleCategoryRename ArticleCategory{ get; set; }

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            ArticleCategory = _articleCategoryApplication.GetBy(id);
        }

        public RedirectToPageResult OnPost()
        {
            _articleCategoryApplication.Rename(ArticleCategory);
            return RedirectToPage("./List");
        }

      
    }
}

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategoryViewModels = new List<ArticleCategoryViewModel>();
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategoryViewModels = _articleCategoryApplication.List();
        }
        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleCategoryApplication.Remove(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleCategoryApplication.Active(id);
            return RedirectToPage("./List");

        }
    }
}

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MB.Application.Contracts.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement
{
    public class ListModel : PageModel
    {

        public  List<ArticleViewModel> Articles = new List<ArticleViewModel>();
        private readonly IArticleApplication _articleApplication;

        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.List();
        }
    }
}

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.MVCCore.Areas.Administrator.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MasterBlogger/MB.Presentation.MVCCore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MB.Presentation.MVCCore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MasterBlogger/MB.Presentation.MVCCore/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MB.Presentation.MVCCore
{
    public class IndexModel : PageModel
    {
        


        public void OnGet()
        {

        }
    }
}

MasterBlogger/MB.Presentation.MVCCore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MB.Presentation.MVCCore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/Create.cshtml
@page
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement.CreateModel
@{
}
<div class="card">
    <div class="card-header">
        <h2>Create New Article Category</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Title" class="control-label">Title:</label>
                            <input name="Title" id="Title" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-success" />
                        <a class="btn btn-dark" asp-page="./List" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/Edit.cshtml
@page
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement.EditModel
@{
}
<div class="card">
    <div class="card-header">
        <h2>Edit Article Category: @Model.ArticleCategory.Title</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ArticleCategory.Id" />
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="ArticleCategory.Title" class="control-label">Title:</label>
                            <input asp-for="ArticleCategory.Title" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Edit" class="btn btn-warning" />
                        <a class="btn btn-dark" asp-page="./List" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleCategoryManagement/List.cshtml
@page
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleCategoryManagement.ListModel
@{
    <div class="card">
        <div class="card-header">
            <h3 class="float-left">Article Category List</h3>
            <div class="float-right">
                <a class="btn btn-success" asp-page="./Create" asp-area="Administrator">Add New</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>CreationDate</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var articleCategory in Model.ArticleCategoryViewModels)
                    {
                        <tr>
                            <td>@articleCategory.Id</td>
                            <td>@articleCategory.Title</td>
                            <td>
                                @if (articleCategory.IsDeleted)
                                {
                                    <i class="fa fa-close fa-2x text-danger"></i>
                                }
                                else
                                {
                                    <i class="fa fa-check fa-2x text-success"></i>
                                }
                            </td>
                            <td>@articleCategory.CreationDate</td>
                            <td>
                                <a class="btn btn-warning float-left mr-3" asp-page="./Edit" asp-route-id="@articleCategory.Id">Rename</a>
                                @if (articleCategory.IsDeleted)
                                {
                                    <form method="post" asp-page-handler="Activate" class="float-left">
                                        <button class="btn btn-success">Activate</button>
                                        <input type="hidden" name="id" value="@articleCategory.Id" />
                                    </form>
                                }
                                else
                                {
                                    <form method="post" asp-page-handler="Remove" class="float-left">
                                        <button class="btn btn-danger">Remove</button>
                                        <input type="hidden" name="id" value="@articleCategory.Id" />
                                    </form>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/ArticleManagement/List.cshtml
@page
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.ArticleManagement.ListModel
@{
}
<div class="card">
    <div class="card-header">
        <h3 class="float-left">Article List</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-page="./Create" asp-area="Administrator">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Article Category</th>
                    <th>Status</th>
                    <th>CreationDate</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var article in Model.Articles)
                {
                    <tr>
                        <td>@article.Id</td>
                        <td>@article.Title</td>
                        <td>@article.ArticleCategory</td>
                        <td>
                            @if (article.IsDeleted)
                            {
                                <i class="fa fa-close fa-2x text-danger"></i>
                            }
                            else
                            {
                                <i class="fa fa-check fa-2x text-success"></i>
                            }
                        </td>
                        <td>@article.CreationDate</td>
                        <td>
                            <a class="btn btn-warning float-left mr-3" asp-page="./Edit" asp-route-id="@article.Id">Edit</a>
                            @if (article.IsDeleted)
                            {
                                <form method="post" asp-page-handler="Activate" class="float-left">
                                    <button class="btn btn-success">Activate</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="Remove" class="float-left">
                                    <button class="btn btn-danger">Remove</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/Index.cshtml
@page
@model MB.Presentation.MVCCore.Areas.Administrator.Pages.IndexModel
@{
}

MasterBlogger/MB.Presentation.MVCCore/Areas/Administrator/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Onion.Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.min.css">
</head>

<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">Onion.Presentation</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Administrator" asp-page="/ArticleCategoryManagement/List">ArticleCategoryManagement</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Administrator" asp-page="/ArticleManagement/List">ArticleManagement</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Administrator" asp-page="/CommentManagement/List">CommentManagement</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light btn btn-info" asp-area="" asp-page="/Index">Visit Site</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Onion.Presentation - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>

MasterBlogger/MB.Presentation.MVCCore/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MasterBlogger/MB.Presentation.MVCCore/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MB.Presentation.MVCCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MB.Presentation.MVCCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MB.Presentation.MVCCore - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>